//! Music and sound effects (`assets/audio`, generated by `tools/gen_audio.py`).
//!
//! The music follows the game: the title theme in menus, the map's track for
//! the current time of day (`LevelDef`), story overrides
//! (`StoryEffect::Music`) and battle themes. Tracks cross-fade. Other systems
//! request sounds by writing an [`Sfx`] message.

use bevy::{audio::Volume, prelude::*};

use crate::{
    GameState, PlayState,
    asset::GameAssets,
    battle::BattleSession,
    content::Content,
    flow::ActionQueue,
    input::MenuInput,
    pause_menu::{Settings, VOLUME_STEPS},
    story::Progress,
};

/// Seconds for a full cross-fade between two tracks.
const FADE_SECS: f32 = 1.4;
/// Music sits below the sound effects in the mix.
const MUSIC_GAIN: f32 = 0.7;

/// Sound effect IDs (`assets/audio/sfx/<id>.ogg`).
pub mod sound {
    pub const UI_MOVE: &str = "ui_move";
    pub const UI_CONFIRM: &str = "ui_confirm";
    pub const UI_CANCEL: &str = "ui_cancel";
    pub const TEXT: &str = "text";
    pub const HIT: &str = "hit";
    pub const HIT_HEAVY: &str = "hit_heavy";
    pub const HEAL: &str = "heal";
    pub const SHIELD: &str = "shield";
    pub const CHARGE: &str = "charge";
    pub const INTERRUPT: &str = "interrupt";
    pub const FORMATION: &str = "formation";
    pub const PICKUP: &str = "pickup";
    pub const QUEST: &str = "quest";
    pub const SAVE: &str = "save";
    pub const WARP: &str = "warp";
    pub const VICTORY: &str = "victory";
    pub const DEFEAT: &str = "defeat";

    /// Every sound above, for the asset test.
    #[cfg(test)]
    pub const ALL: &[&str] = &[
        UI_MOVE, UI_CONFIRM, UI_CANCEL, TEXT, HIT, HIT_HEAVY, HEAL, SHIELD, CHARGE, INTERRUPT,
        FORMATION, PICKUP, QUEST, SAVE, WARP, VICTORY, DEFEAT,
    ];
}

/// Request to play a sound effect by id (`assets/audio/sfx/<id>.ogg`).
#[derive(Message, Clone, Copy, Debug, PartialEq, Eq)]
pub struct Sfx(pub &'static str);

#[derive(Component)]
struct MusicTrack {
    id: String,
    /// Fade level, 0 (silent) to 1 (full).
    level: f32,
    leaving: bool,
}

/// What the music should do this frame.
#[derive(Debug, Clone, PartialEq, Eq)]
enum Want {
    /// Keep whatever is playing (loading screens, cards).
    Keep,
    Silence,
    Track(String),
}

#[derive(Resource, Default)]
struct CurrentMusic(Option<String>);

pub struct GameAudioPlugin;

impl Plugin for GameAudioPlugin {
    fn build(&self, app: &mut App) {
        app.add_message::<Sfx>()
            .init_resource::<CurrentMusic>()
            .add_systems(
                Update,
                (choose_music, fade_music, battle_jingle, ui_sounds, play_sfx)
                    .chain()
                    .run_if(resource_exists::<GameAssets>),
            );
    }
}

/// The track a battle uses: its own, `boss` with a boss enemy, else `battle`.
fn battle_track(session: &BattleSession, content: &Content) -> String {
    let state = &session.state;
    if let Some(track) = content
        .db
        .encounters
        .get(&state.encounter)
        .and_then(|e| e.music.clone())
    {
        return track;
    }
    let boss = state
        .units
        .iter()
        .filter_map(|u| content.db.enemies.get(&u.def))
        .any(|e| e.boss);
    if boss { "boss" } else { "battle" }.to_string()
}

/// The map's track for the current time of day, or the story override.
fn exploring_track(progress: &Progress, content: &Content) -> Want {
    if let Some(track) = &progress.music {
        return Want::Track(track.clone());
    }
    match content.db.levels.get(&progress.level) {
        Some(level) => Want::Track(
            level
                .music_by_time
                .get(&progress.time)
                .unwrap_or(&level.music)
                .clone(),
        ),
        None => Want::Keep,
    }
}

#[allow(clippy::too_many_arguments)]
fn choose_music(
    mut commands: Commands,
    assets: Res<GameAssets>,
    content: Option<Res<Content>>,
    game: Res<State<GameState>>,
    play: Option<Res<State<PlayState>>>,
    progress: Option<Res<Progress>>,
    battle: Option<Res<BattleSession>>,
    queue: Res<ActionQueue>,
    next_play: Option<Res<NextState<PlayState>>>,
    mut current: ResMut<CurrentMusic>,
    mut tracks: Query<&mut MusicTrack>,
) {
    let want = match (game.get(), play.as_deref().map(State::get)) {
        (GameState::Loading, _) => Want::Silence,
        (GameState::Menu | GameState::CharacterCreation, _) => Want::Track("title".into()),
        (GameState::Starting, _)
        | (GameState::Playing, None | Some(PlayState::Card | PlayState::Transition)) => Want::Keep,
        (GameState::Playing, Some(PlayState::Battle)) => match (&battle, &content) {
            (Some(session), _) if session.state.is_over() => Want::Silence,
            (Some(session), Some(content)) => Want::Track(battle_track(session, content)),
            _ => Want::Keep,
        },
        // A queued battle or scene is about to start; don't flash the map track.
        (GameState::Playing, Some(PlayState::Exploring))
            if !queue.0.is_empty()
                || next_play
                    .as_deref()
                    .is_some_and(|n| matches!(n, NextState::Pending(_))) =>
        {
            Want::Keep
        }
        (GameState::Playing, Some(_)) => match (&progress, &content) {
            (Some(progress), Some(content)) => exploring_track(progress, content),
            _ => Want::Keep,
        },
    };
    let next = match want {
        Want::Keep => return,
        Want::Silence => None,
        Want::Track(id) => Some(id),
    };
    if next == current.0 {
        return;
    }
    for mut track in &mut tracks {
        track.leaving = Some(&track.id) != next.as_ref();
    }
    if let Some(id) = &next
        && !tracks.iter().any(|t| &t.id == id)
    {
        match assets.music_track(id) {
            Some(handle) => {
                commands.spawn((
                    Name::new(format!("Music {id}")),
                    MusicTrack {
                        id: id.clone(),
                        level: 0.0,
                        leaving: false,
                    },
                    AudioPlayer::new(handle),
                    PlaybackSettings::LOOP.with_volume(Volume::Linear(0.0)),
                ));
            }
            None => warn!("music track `{id}` not found"),
        }
    }
    info!("music: {}", next.as_deref().unwrap_or("(silence)"));
    current.0 = next;
}

fn fade_music(
    mut commands: Commands,
    time: Res<Time>,
    settings: Res<Settings>,
    mut tracks: Query<(Entity, &mut MusicTrack, Option<&mut AudioSink>)>,
) {
    let step = time.delta_secs() / FADE_SECS;
    let master = f32::from(settings.music_volume) / f32::from(VOLUME_STEPS) * MUSIC_GAIN;
    for (entity, mut track, sink) in &mut tracks {
        track.level = if track.leaving {
            (track.level - step).max(0.0)
        } else {
            (track.level + step).min(1.0)
        };
        if track.leaving && track.level == 0.0 {
            commands.entity(entity).despawn();
            continue;
        }
        if let Some(mut sink) = sink {
            // Squared fade sounds more even than a linear one.
            sink.set_volume(Volume::Linear(track.level * track.level * master));
        }
    }
}

/// Victory and defeat jingles when a battle ends.
fn battle_jingle(
    session: Option<Res<BattleSession>>,
    mut sfx: MessageWriter<Sfx>,
    mut played: Local<bool>,
) {
    let Some(session) = session else {
        *played = false;
        return;
    };
    if !session.state.is_over() {
        *played = false;
        return;
    }
    if !*played {
        *played = true;
        let victory = session.state.phase == crate::battle::core::Phase::Victory;
        sfx.write(Sfx(if victory {
            sound::VICTORY
        } else {
            sound::DEFEAT
        }));
    }
}

/// Menu navigation sounds, read straight from the shared input.
fn ui_sounds(
    input: Res<MenuInput>,
    game: Res<State<GameState>>,
    play: Option<Res<State<PlayState>>>,
    battle: Option<Res<BattleSession>>,
    mut sfx: MessageWriter<Sfx>,
) {
    let menu_like = match (game.get(), play.as_deref().map(State::get)) {
        (GameState::Menu | GameState::CharacterCreation, _) => true,
        (
            GameState::Playing,
            Some(PlayState::Paused | PlayState::Dialogue | PlayState::Workshop),
        ) => true,
        (GameState::Playing, Some(PlayState::Battle)) => battle.is_some_and(|b| {
            b.state.is_over() || matches!(b.state.phase, crate::battle::core::Phase::Command(_))
        }),
        _ => false,
    };
    if !menu_like {
        return;
    }
    let in_dialogue = matches!(play.as_deref().map(State::get), Some(PlayState::Dialogue));
    if input.cancel {
        sfx.write(Sfx(sound::UI_CANCEL));
    } else if input.confirm {
        sfx.write(Sfx(if in_dialogue {
            sound::TEXT
        } else {
            sound::UI_CONFIRM
        }));
    } else if input.up || input.down || input.left || input.right {
        sfx.write(Sfx(sound::UI_MOVE));
    }
}

fn play_sfx(
    mut commands: Commands,
    assets: Res<GameAssets>,
    settings: Res<Settings>,
    mut requests: MessageReader<Sfx>,
) {
    let volume = f32::from(settings.sfx_volume) / f32::from(VOLUME_STEPS);
    let mut played: Vec<&'static str> = Vec::new();
    for Sfx(id) in requests.read() {
        // Several identical hits in one frame would only get louder.
        if volume <= 0.0 || played.contains(id) {
            continue;
        }
        played.push(id);
        match assets.sound(id) {
            Some(handle) => {
                commands.spawn((
                    AudioPlayer::new(handle),
                    PlaybackSettings::DESPAWN.with_volume(Volume::Linear(volume)),
                ));
            }
            None => warn!("sound `{id}` not found"),
        }
    }
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    #[test]
    fn every_sound_effect_exists() {
        let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("assets/audio/sfx");
        for id in super::sound::ALL {
            assert!(
                dir.join(format!("{id}.ogg")).exists(),
                "missing sound `{id}`"
            );
        }
    }
}
